import os


# Project variables
PROCESS_NAME = os.path.basename(os.path.dirname(__file__))
PROCESS_VERSION = '1.1.0'

# Timeouts
IGNORED_DEVICES_TIMEOUT = 600  # 10 min
DEVICE_SERVICES_TIMEOUT = 1800  # 30 min
SCAN_TIMEOUT = 15
SCAN_INTERVAL_STANDARD = 20  # 90
SCAN_SLEEP = max(0, SCAN_INTERVAL_STANDARD - SCAN_TIMEOUT)
